### ISSUE TITLE
How to generate label files(.txt) for Darknet?

### ISSUE THREAD

**Issue by msarfrazcss** [szaza/dataset-generator#2]
Hi,

I want to train a model on my custom dataset, but I have only annotation files(.xml) for all images and i want to create label files from these annotation files. Is there any way to do that.

**Comment by szaza** [comment]
Hi,
Unfortunately, this dataset generator is not able to to make conversion between annotation files and label files. It creates the dataset from images and backgrounds.

**Comment by msarfrazcss** [comment]
Thanks
Can i generate my own dataset on my images by using your tool.

**Comment by szaza** [comment]
Yes, you can. Please see the description here: https://sites.google.com/view/tensorflow-example-java-api/dataset-generator.

**Comment by msarfrazcss** [comment]
Thanks, i got it.
